export const skills = {
  languages: {
    label: 'Programming Languages',
    icon: 'fa-solid fa-code',
    items: ['Python', 'Java', 'C', 'C++', 'C#', 'HTML', 'CSS', 'Javascript', 'R'],
  },
  frameworks: {
    label: 'Libraries & Frameworks',
    icon: 'fa-solid fa-cubes',
    items: ['Sklearn', 'TensorFlow', 'Gym', 'Pandas', 'Stable Baselines', 'Flask', 'Rasa'],
  },
  tools: {
    label: 'Tools & Platforms',
    icon: 'fa-solid fa-gears',
    items: ['MySQL', 'Unity', 'Docker', 'Kubernetes', 'AWS', 'Azure', 'GitHub Actions', 'Redis', 'UIPath'],
  },
};

export const projects = [
  {
    id: 1,
    title: 'Sentinel AI',
    description: 'ML based threat detection system. Identify cyberattacks via email and messages.',
    image: 'images/cybersecurity.jpg',
    github: 'https://github.com/MeTuL10/Sentinel-AI',
    tags: ['ML', 'Security'],
  },
  {
    id: 2,
    title: 'Portfolio Optimization',
    description: 'Application of multiple RL models on a multi-stock trading environment to analyze performance and maximise profit.',
    image: 'images/rl.jpg',
    github: 'https://github.com/MeTuL10/Reinforcement_learning_portfolio_optimization',
    tags: ['RL', 'Finance'],
  },
  {
    id: 3,
    title: 'Early Suicide Prediction',
    description: 'Prediction of suicidal ideation using deep learning models and preprocessing techniques for refinement of data.',
    image: 'images/dl.jpg',
    github: 'https://github.com/MeTuL10/TARP_early_suicide_prediction',
    tags: ['DL', 'NLP'],
  },
  {
    id: 4,
    title: 'Online Streaming Analytics',
    description: 'Analytics on Twitch streamers using supervised and unsupervised ML models to classify streamers and predict their growth.',
    image: 'images/eda.jpg',
    github: 'https://github.com/MeTuL10/online-streaming-analytics',
    tags: ['ML', 'Analytics'],
  },
  {
    id: 5,
    title: 'Diabetes Prediction App',
    description: 'Web application deployed to AWS for predicting diabetes using a DL model.',
    image: 'images/diabetes.jpg',
    github: 'https://github.com/MeTuL10/diabetes-predictor',
    tags: ['DL', 'AWS'],
  },
  {
    id: 6,
    title: 'Maze Escape',
    description: 'Game developed using Unity and C# for implementing pathfinding algorithms.',
    image: 'images/maze.jpg',
    github: 'https://github.com/MeTuL10/Maze-escape-Unity',
    tags: ['Unity', 'C#'],
  },
  {
    id: 7,
    title: 'E-Waiter',
    description: 'Python application created using Tkinter, speech to text and MySQL.',
    image: 'images/restaurant.jpg',
    github: 'https://github.com/MeTuL10/e-waiter',
    tags: ['Python', 'NLP'],
  },
  {
    id: 8,
    title: 'Rasa Chatbot',
    description: 'Chatbot developed using Rasa framework and deployed using Docker and GitHub Actions to Azure.',
    image: 'images/chat.jpg',
    github: 'https://github.com/MeTuL10/rasachatbot',
    tags: ['Rasa', 'DevOps'],
  },
  {
    id: 9,
    title: 'IBM DevOps Capstone',
    description: 'A customer account management application developed and deployed using DevOps practices, guided by IBM DevOps certification.',
    image: 'images/devops.jpg',
    github: 'https://github.com/MeTuL10/devops-capstone-project',
    tags: ['DevOps', 'IBM'],
  },
  {
    id: 10,
    title: 'EZ Ticket',
    description: 'RPA for booking train and flight tickets using UIPath.',
    image: 'images/rpa.jpg',
    github: 'https://github.com/MeTuL10/EZTicket',
    tags: ['RPA', 'UIPath'],
  },
  {
    id: 11,
    title: 'Personal Portfolio',
    description: 'Personal portfolio website developed using HTML and CSS and deployed through GitHub.',
    image: 'images/website.jpg',
    github: 'https://github.com/MeTuL10/personal-portfolio',
    tags: ['HTML', 'CSS'],
  },
];

export const artworks = [
  {
    id: 1,
    title: 'Genshin Impact – Zhongli',
    image: 'images/artworks/zhongli bg1.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Zhongli-genshin-impact-963795112',
  },
  {
    id: 2,
    title: 'Genshin Impact – Childe',
    image: 'images/artworks/childe.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Childe-genshin-impact-963799355',
  },
  {
    id: 3,
    title: 'Demon Slayer – Tanjirou',
    image: 'images/artworks/tanjiro.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Tanjirou-demon-slayer-965400438',
  },
  {
    id: 4,
    title: 'Fairy Tail – Natsu & Ignia',
    image: 'images/artworks/firedragons1.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Fairy-tail-fire-dragons-963793798',
  },
  {
    id: 5,
    title: 'Fairy Tail Guild Crest',
    image: 'images/artworks/ft.png',
    link: 'https://www.deviantart.com/metalex10/art/fairy-tail-963795456',
  },
  {
    id: 6,
    title: 'Haikyuu – Hinata & Kageyama',
    image: 'images/artworks/hinakags v4.jpg',
    link: 'https://www.deviantart.com/metalex10/art/haikyuu-hinata-and-kageyama-963794575',
  },
  {
    id: 7,
    title: 'Jujutsu Kaisen – Gojo Satoru',
    image: 'images/artworks/gojo.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Gojo-963794936',
  },
  {
    id: 8,
    title: 'Across the Spider-Verse',
    image: 'images/artworks/Across the spiderverse.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Across-the-spiderverse-965581737',
  },
  {
    id: 9,
    title: 'Monster – Tenma & Johan',
    image: 'images/artworks/monster.jpg',
    link: 'https://www.deviantart.com/metalex10/art/johan-and-tenma-963805141',
  },
  {
    id: 10,
    title: 'Spider-Verse – The Spot',
    image: 'images/artworks/Spiderverse-spot.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Spiderverse-spot-971562722',
  },
  {
    id: 11,
    title: 'Genshin Impact – Zhongli II',
    image: 'images/artworks/zhongli.jpg',
    link: 'https://www.deviantart.com/metalex10/art/Zhongli-genshin-impact-964710078',
  },
  {
    id: 12,
    title: 'Nanatsu no Taizai – Meliodas',
    image: 'images/artworks/nanatsu.png',
    link: 'https://www.deviantart.com/metalex10/art/meliodas-nanatsu-no-taizai-963803335',
  },
];
